/**
 * Hope Mission LRF — demo seed data
 *
 * DEMO ONLY — Remove or disable getSeedStore() / POST /api/seed and the
 * "Reset Demo Data" control before deploying with real organisational data.
 *
 * All names and Employee IDs are fictional (e.g. ZEL009, SMI001).
 */

const { summarizeLeaveTypes } = require("./constants");
const { computeReviewMarkers, snapshotRecord } = require("./manusonic-logic");

function enrichRequest(r, employees) {
  const emp = employees.find((e) => e.id === r.empId);
  const base = {
    source: r.source || "portal",
    formResponseId: r.formResponseId || null,
    formType: r.formType || null,
    jobTitle: r.jobTitle || emp?.jobRole || "",
    yearOfLeave: r.yearOfLeave || "2026",
    additionalNotes: r.additionalNotes || r.reason || "",
    dayLabels: r.dayLabels || (r.leaveDates || []).join(", "),
    verificationStatus:
      r.verificationStatus ||
      (r.postedToManusonic ? "posted" : r.status === "taken" ? "verified" : "needs_review"),
    postedToManusonic: !!r.postedToManusonic,
    postedAt: r.postedAt || null,
    postedBy: r.postedBy || null,
    proxySubmission: !!r.proxySubmission,
    correctionsMade: !!r.correctionsMade,
    verifiedBy: r.verifiedBy || null,
    verifiedByName: r.verifiedByName || null,
    verifiedAt: r.verifiedAt || null,
    auditTrail: r.auditTrail || [],
    reviewMarkers: r.reviewMarkers || [],
    originalSubmission: r.originalSubmission || null,
    supervisorSubmissionFlag: !!r.supervisorSubmissionFlag,
    matchedByName: !!r.matchedByName,
    unmatched: !!r.unmatched,
    originalSubmittedAt: r.originalSubmittedAt || r.submittedAt,
  };
  const merged = { ...r, ...base };
  if (!merged.originalSubmission) {
    merged.originalSubmission = snapshotRecord({
      empId: merged.empId,
      empName: merged.empName,
      jobTitle: merged.jobTitle,
      department: merged.department,
      costCentre: merged.costCentre,
      employmentType: merged.employmentType,
      payPeriodLabel: merged.payPeriodLabel,
      yearOfLeave: merged.yearOfLeave,
      days: merged.days,
      dayLabels: merged.dayLabels,
      shiftLength: merged.shiftLength,
      hourDistribution: merged.hourDistribution,
      totalHours: merged.totalHours,
      additionalNotes: merged.additionalNotes,
      formResponseId: merged.formResponseId,
      submittedAt: merged.submittedAt,
    });
  }
  if (!merged.reviewMarkers.length && merged.verificationStatus === "needs_review" && !merged.unmatched) {
    merged.reviewMarkers = computeReviewMarkers(merged, emp, emp);
  }
  if (merged.unmatched && !merged.reviewMarkers.length) {
    merged.reviewMarkers = [{ code: "unmatched", hint: "Employee could not be matched in directory — please assign correct Employee ID" }];
  }
  return merged;
}

function lastNamePrefix(fullName) {
  const parts = String(fullName || "").trim().split(/\s+/);
  const last = parts[parts.length - 1] || fullName;
  const letters = last.replace(/[^a-zA-Z]/g, "").toUpperCase();
  return (letters + "XXX").slice(0, 3);
}

function assignEmployeeIds(employees) {
  const seq = {};
  return employees.map((emp) => {
    const prefix = lastNamePrefix(emp.name);
    seq[prefix] = (seq[prefix] || 0) + 1;
    const id = prefix + String(seq[prefix]).padStart(3, "0");
    return { ...emp, id };
  });
}

function getSeedStore() {
  const employees = [
    {
      id: "EXE001",
      name: "Cameron Reid",
      email: "c.reid@hopemission.demo",
      initials: "CR",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      jobRole: "Executive Director",
      systemRole: "admin",
      employmentType: "RFT Salaried",
      skipApproval: true,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "ADM001",
      name: "Morgan Price",
      email: "m.price@hopemission.demo",
      initials: "MP",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      jobRole: "Admin Manager",
      systemRole: "admin",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "HRH001",
      name: "Riley Hart",
      email: "r.hart@hopemission.demo",
      initials: "RH",
      department: "Human Resources",
      costCentre: "5100",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      jobRole: "Human Resources",
      systemRole: "hr",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "MAN001",
      name: "Jordan Mercer",
      email: "j.mercer@hopemission.demo",
      initials: "JM",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      jobRole: "Shelter Manager",
      systemRole: "manager",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "MAN002",
      name: "Tessa Okonkwo",
      email: "t.okonkwo@hopemission.demo",
      initials: "TO",
      department: "Food Services",
      costCentre: "7200",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      jobRole: "Food Services Manager",
      systemRole: "manager",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "FAR001",
      name: "Fiona Archer",
      email: "f.archer@hopemission.demo",
      initials: "FA",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      jobRole: "Shelter Support Worker",
      systemRole: null,
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "WEL003",
      name: "Elena Wells",
      email: "e.wells@hopemission.demo",
      initials: "EW",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      jobRole: "Overnight Shelter Worker",
      systemRole: null,
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "ZEL009",
      name: "Ayla Zelinski",
      email: "a.zelinski@hopemission.demo",
      initials: "AZ",
      department: "Food Services",
      costCentre: "7200",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      jobRole: "Kitchen Assistant",
      systemRole: null,
      employmentType: "RFT Hourly",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "SMI001",
      name: "Connor Smith",
      email: "c.smith@hopemission.demo",
      initials: "CS",
      department: "Volunteer Services",
      costCentre: "5400",
      managerId: "HRH001",
      managerName: "Riley Hart",
      jobRole: "Volunteer Coordinator (Contract)",
      systemRole: null,
      employmentType: "FTT",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "NAK002",
      name: "Priya Nakamura",
      email: "p.nakamura@hopemission.demo",
      initials: "PN",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      jobRole: "Community Outreach Worker",
      systemRole: null,
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "HUG001",
      name: "Marcus Hughes",
      email: "m.hughes@hopemission.demo",
      initials: "MH",
      department: "Programs & Outreach",
      costCentre: "6900",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      jobRole: "Program Facilitator",
      systemRole: null,
      employmentType: "RFT Hourly",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "TOR001",
      name: "Devon Torres",
      email: "d.torres@hopemission.demo",
      initials: "DT",
      department: "Food Services",
      costCentre: "7200",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      jobRole: "Line Cook",
      systemRole: null,
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "LIN002",
      name: "Avery Lin",
      email: "a.lin@hopemission.demo",
      initials: "AL",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      jobRole: "Intake Worker",
      systemRole: null,
      employmentType: "RFT Hourly",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "PAT004",
      name: "Jordan Patel",
      email: "j.patel@hopemission.demo",
      initials: "JP",
      department: "Programs & Outreach",
      costCentre: "6900",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      jobRole: "Relief Program Worker",
      systemRole: null,
      employmentType: "FTT",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "COX001",
      name: "Sam Cox",
      email: "s.cox@hopemission.demo",
      initials: "SC",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "ADM001",
      managerName: "Morgan Price",
      jobRole: "Administrative Assistant",
      systemRole: null,
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "ADM002",
      name: "Dana Okafor",
      email: "d.okafor@hopemission.demo",
      initials: "DO",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      jobRole: "Admin Coordinator",
      systemRole: "admin",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "AST001",
      name: "Robin Vega",
      email: "r.vega@hopemission.demo",
      initials: "RV",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "ADM001",
      managerName: "Morgan Price",
      jobRole: "Admin Assistant",
      systemRole: "admin",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
    {
      id: "HRH002",
      name: "Sasha Bello",
      email: "s.bello@hopemission.demo",
      initials: "SB",
      department: "Human Resources",
      costCentre: "5100",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      jobRole: "HR Generalist",
      systemRole: "hr",
      employmentType: "RFT Salaried",
      skipApproval: false,
      active: true,
      employmentTypeHistory: [],
      needsEmploymentType: false,
    },
  ];

  const PP_APR_MAY = "April 21 – May 20";
  const PP_MAY_JUN = "May 21 – June 20";
  const PP_JUN_JUL = "June 21 – July 20";

  const requests = [
    /* 1 — Normal pending (awaiting manager, Needs Review) */
    {
      id: "MS-DEMO-001",
      source: "microsoft_forms",
      formResponseId: "DEMO-001",
      formType: "salaried",
      empId: "FAR001",
      empName: "Fiona Archer",
      initials: "FA",
      jobTitle: "Shelter Support Worker",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Paid Sick Leave",
      leaveDates: ["2026-05-14", "2026-05-15"],
      dayLabels: "2026-05-14, 2026-05-15",
      days: 2,
      payPeriod: { start: "2026-04-21", end: "2026-05-20", label: PP_APR_MAY },
      payPeriodLabel: PP_APR_MAY,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Paid Sick Leave", hours: 16 }],
      totalHours: 16,
      shiftLength: "8 Hours",
      reason: "Flu — resting at home.",
      additionalNotes: "Flu — resting at home.",
      status: "pending",
      verificationStatus: "needs_review",
      payStatus: "paid",
      submittedAt: "2026-05-13T09:15:00.000Z",
      originalSubmittedAt: "5/13/2026 9:15",
      approvedById: null,
      approvedByName: null,
    },
    /* 2 — Manager-approved → verified, pending Manusonic entry */
    {
      id: "MS-DEMO-002",
      source: "microsoft_forms",
      formResponseId: "DEMO-002",
      formType: "salaried",
      empId: "NAK002",
      empName: "Priya Nakamura",
      initials: "PN",
      jobTitle: "Community Outreach Worker",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Personal Day",
      leaveDates: ["2026-05-06"],
      dayLabels: "2026-05-06",
      days: 1,
      payPeriod: { start: "2026-04-21", end: "2026-05-20", label: PP_APR_MAY },
      payPeriodLabel: PP_APR_MAY,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Medical appointment.",
      additionalNotes: "Medical appointment.",
      status: "approved",
      verificationStatus: "verified",
      payStatus: "paid",
      submittedAt: "2026-05-05T11:00:00.000Z",
      originalSubmittedAt: "5/5/2026 11:00",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-05-05T14:30:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-05-06T10:00:00.000Z",
      managerComment: "Approved.",
    },
    /* 3 — Posted to Manusonic (locked) */
    {
      id: "MS-DEMO-003",
      source: "microsoft_forms",
      formResponseId: "DEMO-003",
      formType: "salaried",
      empId: "WEL003",
      empName: "Elena Wells",
      initials: "EW",
      jobTitle: "Overnight Shelter Worker",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Bereavement",
      leaveDates: ["2026-04-22", "2026-04-23", "2026-04-24"],
      dayLabels: "2026-04-22, 2026-04-23, 2026-04-24",
      days: 3,
      payPeriod: { start: "2026-04-21", end: "2026-05-20", label: PP_APR_MAY },
      payPeriodLabel: PP_APR_MAY,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Bereavement", hours: 24 }],
      totalHours: 24,
      shiftLength: "8 Hours",
      reason: "Family bereavement — travel required.",
      additionalNotes: "Family bereavement — travel required.",
      status: "approved",
      verificationStatus: "posted",
      payStatus: "paid",
      submittedAt: "2026-04-21T08:00:00.000Z",
      originalSubmittedAt: "4/21/2026 8:00",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-04-21T12:00:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-04-22T09:00:00.000Z",
      postedToManusonic: true,
      postedAt: "2026-04-23T15:30:00.000Z",
      postedBy: "Morgan Price",
      managerComment: "Approved — condolences.",
    },
    /* 4 — Retroactive / already taken */
    {
      id: "MS-DEMO-004",
      source: "microsoft_forms",
      formResponseId: "DEMO-004",
      formType: "hourly",
      empId: "ZEL009",
      empName: "Ayla Zelinski",
      initials: "AZ",
      jobTitle: "Kitchen Assistant",
      department: "Food Services",
      costCentre: "7200",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      employmentType: "RFT Hourly",
      leaveType: "Without Pay",
      leaveDates: ["2026-03-18"],
      dayLabels: "2026-03-18",
      days: 1,
      payPeriod: { start: "2026-02-21", end: "2026-03-20", label: "February 21 – March 20" },
      payPeriodLabel: "February 21 – March 20",
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Without Pay", hours: 10 }],
      totalHours: 10,
      shiftLength: "10 Hours",
      reason: "Personal emergency — already taken, reporting retroactively.",
      additionalNotes: "Personal emergency — already taken.",
      status: "taken",
      verificationStatus: "verified",
      payStatus: "without_pay",
      submittedAt: "2026-03-19T16:00:00.000Z",
      originalSubmittedAt: "3/19/2026 16:00",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-03-20T11:00:00.000Z",
      managerComment: "Retroactive — recorded.",
    },
    /* 5 — FTT auto Without Pay */
    {
      id: "MS-DEMO-005",
      source: "microsoft_forms",
      formResponseId: "DEMO-005",
      formType: "salaried",
      empId: "SMI001",
      empName: "Connor Smith",
      initials: "CS",
      jobTitle: "Volunteer Coordinator (Contract)",
      department: "Volunteer Services",
      costCentre: "5400",
      managerId: "HRH001",
      managerName: "Riley Hart",
      employmentType: "FTT",
      leaveType: "Without Pay",
      leaveDates: ["2026-06-02"],
      dayLabels: "2026-06-02",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Without Pay", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Contract staff — day without pay.",
      additionalNotes: "Contract staff — day without pay.",
      status: "approved",
      verificationStatus: "verified",
      payStatus: "without_pay",
      fttReviewFlag: false,
      submittedAt: "2026-06-01T10:00:00.000Z",
      originalSubmittedAt: "6/1/2026 10:00",
      approvedById: "HRH001",
      approvedByName: "Riley Hart",
      approvedAt: "2026-06-01T14:00:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-06-02T09:30:00.000Z",
    },
    /* 6 — Multiple categories in one submission */
    {
      id: "MS-DEMO-006",
      source: "microsoft_forms",
      formResponseId: "DEMO-006",
      formType: "salaried",
      empId: "TOR001",
      empName: "Devon Torres",
      initials: "DT",
      jobTitle: "Line Cook",
      department: "Food Services",
      costCentre: "7200",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      employmentType: "RFT Salaried",
      leaveType: "Vacation · OT Banked",
      leaveDates: ["2026-07-08", "2026-07-09", "2026-07-10"],
      dayLabels: "2026-07-08, 2026-07-09, 2026-07-10",
      days: 3,
      payPeriod: { start: "2026-06-21", end: "2026-07-20", label: PP_JUN_JUL },
      payPeriodLabel: PP_JUN_JUL,
      yearOfLeave: "2026",
      hourDistribution: [
        { type: "Vacation", hours: 16 },
        { type: "OT Banked", hours: 8 },
      ],
      totalHours: 24,
      shiftLength: "8 Hours",
      reason: "Summer break — mix of vacation and banked OT.",
      additionalNotes: "Summer break.",
      status: "approved",
      verificationStatus: "verified",
      payStatus: "paid",
      submittedAt: "2026-06-25T09:00:00.000Z",
      originalSubmittedAt: "6/25/2026 9:00",
      approvedById: "MAN002",
      approvedByName: "Tessa Okonkwo",
      approvedAt: "2026-06-25T13:00:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-06-26T10:00:00.000Z",
    },
    /* 7 — Proxy submission (supervisor corrected to absent employee) */
    {
      id: "MS-DEMO-007",
      source: "microsoft_forms",
      formResponseId: "DEMO-007",
      formType: "salaried",
      empId: "FAR001",
      empName: "Fiona Archer",
      initials: "FA",
      jobTitle: "Shelter Support Worker",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Compassionate Care",
      leaveDates: ["2026-05-28"],
      dayLabels: "2026-05-28",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Compassionate Care", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Family emergency — confirmed absent.",
      additionalNotes: "Submitted by supervisor on behalf of absent staff.",
      status: "approved",
      verificationStatus: "verified",
      payStatus: "paid",
      proxySubmission: true,
      correctionsMade: true,
      supervisorSubmissionFlag: true,
      submittedAt: "2026-05-27T07:30:00.000Z",
      originalSubmittedAt: "5/27/2026 7:30",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-05-27T11:00:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-05-28T08:45:00.000Z",
      originalSubmission: {
        empId: "MAN001",
        empName: "Jordan Mercer",
        jobTitle: "Shelter Manager",
        department: "Shelters & Housing",
        costCentre: "7800",
        employmentType: "RFT Salaried",
        payPeriodLabel: PP_MAY_JUN,
        yearOfLeave: "2026",
        days: 1,
        dayLabels: "2026-05-28",
        shiftLength: "8 Hours",
        hourDistribution: [{ type: "Compassionate Care", hours: 8 }],
        totalHours: 8,
        additionalNotes: "Submitted for absent staff — Fiona Archer.",
        formResponseId: "DEMO-007",
        submittedAt: "2026-05-27T07:30:00.000Z",
      },
      auditTrail: [
        {
          originalEmpId: "MAN001",
          originalEmpName: "Jordan Mercer",
          correctedEmpId: "FAR001",
          correctedEmpName: "Fiona Archer",
          originalValues: {
            empId: "MAN001",
            empName: "Jordan Mercer",
            hourDistribution: [{ type: "Compassionate Care", hours: 8 }],
            totalHours: 8,
          },
          correctedValues: {
            empId: "FAR001",
            empName: "Fiona Archer",
            hourDistribution: [{ type: "Compassionate Care", hours: 8 }],
            totalHours: 8,
          },
          correctionReason: "Submitted on behalf of absent staff member (supervisor submitted for employee)",
          correctionNote: "Jordan Mercer submitted on behalf of Fiona Archer who was unable to access the form. Confirmed by phone with Fiona and shift log.",
          submittedBySupervisor: "Jordan Mercer",
          adminName: "Morgan Price",
          adminId: "ADM001",
          timestamp: "2026-05-28T08:45:00.000Z",
        },
      ],
    },
    /* 8 — Zero-hours flag in Needs Review */
    {
      id: "MS-DEMO-008",
      source: "microsoft_forms",
      formResponseId: "DEMO-008",
      formType: "salaried",
      empId: "COX001",
      empName: "Sam Cox",
      initials: "SC",
      jobTitle: "Administrative Assistant",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "ADM001",
      managerName: "Morgan Price",
      employmentType: "RFT Salaried",
      leaveType: "—",
      leaveDates: ["2026-06-10"],
      dayLabels: "2026-06-10",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [],
      totalHours: 0,
      shiftLength: "8 Hours",
      reason: "Intended leave — hours not entered on form.",
      additionalNotes: "",
      status: "pending",
      verificationStatus: "needs_review",
      payStatus: "paid",
      submittedAt: "2026-06-09T14:20:00.000Z",
      originalSubmittedAt: "6/9/2026 14:20",
      reviewMarkers: [{ code: "zero_total", hint: "Total hours is zero — please confirm" }],
    },
    /* 9 — Unmatched submission (not in directory) */
    {
      id: "MS-DEMO-009",
      source: "microsoft_forms",
      formResponseId: "DEMO-009",
      formType: "hourly",
      empId: "ZZZ999",
      empName: "Robin Vale",
      initials: "RV",
      jobTitle: "",
      department: "",
      costCentre: "",
      managerId: null,
      managerName: null,
      employmentType: "",
      leaveType: "Personal Day",
      leaveDates: ["2026-06-12"],
      dayLabels: "2026-06-12",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Unknown employee ID on form.",
      additionalNotes: "Employee ID VAL999 not found in directory.",
      status: "pending",
      verificationStatus: "needs_review",
      unmatched: true,
      payStatus: "paid",
      submittedAt: "2026-06-11T10:00:00.000Z",
      originalSubmittedAt: "6/11/2026 10:00",
    },
    /* 10 — Same pay period as #2 (snapshot totals) */
    {
      id: "MS-DEMO-010",
      source: "microsoft_forms",
      formResponseId: "DEMO-010",
      formType: "salaried",
      empId: "LIN002",
      empName: "Avery Lin",
      initials: "AL",
      jobTitle: "Intake Worker",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Hourly",
      leaveType: "Paid Sick Leave",
      leaveDates: ["2026-05-19", "2026-05-20"],
      dayLabels: "2026-05-19, 2026-05-20",
      days: 2,
      payPeriod: { start: "2026-04-21", end: "2026-05-20", label: PP_APR_MAY },
      payPeriodLabel: PP_APR_MAY,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Paid Sick Leave", hours: 20 }],
      totalHours: 20,
      shiftLength: "10 Hours",
      reason: "Illness — doctor advised rest.",
      additionalNotes: "Illness.",
      status: "approved",
      verificationStatus: "verified",
      payStatus: "paid",
      submittedAt: "2026-05-18T08:00:00.000Z",
      originalSubmittedAt: "5/18/2026 8:00",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-05-18T12:00:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-05-19T09:00:00.000Z",
    },
    /* 11 — FTT paid-category flag in Needs Review */
    {
      id: "MS-DEMO-011",
      source: "microsoft_forms",
      formResponseId: "DEMO-011",
      formType: "salaried",
      empId: "PAT004",
      empName: "Jordan Patel",
      initials: "JP",
      jobTitle: "Relief Program Worker",
      department: "Programs & Outreach",
      costCentre: "6900",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      employmentType: "FTT",
      leaveType: "Paid Sick Leave",
      leaveDates: ["2026-06-04"],
      dayLabels: "2026-06-04",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Paid Sick Leave", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Medical appointment.",
      additionalNotes: "",
      status: "pending",
      verificationStatus: "needs_review",
      payStatus: "without_pay",
      fttReviewFlag: true,
      submittedAt: "2026-06-03T11:30:00.000Z",
      originalSubmittedAt: "6/3/2026 11:30",
    },
    /* 12 — Executive Director auto-route (skipApproval), verified pending */
    {
      id: "MS-DEMO-012",
      source: "microsoft_forms",
      formResponseId: "DEMO-012",
      formType: "salaried",
      empId: "EXE001",
      empName: "Cameron Reid",
      initials: "CR",
      jobTitle: "Executive Director",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "EXE001",
      managerName: "Cameron Reid",
      employmentType: "RFT Salaried",
      leaveType: "Personal Day",
      leaveDates: ["2026-08-05"],
      dayLabels: "2026-08-05",
      days: 1,
      payPeriod: { start: "2026-07-21", end: "2026-08-20", label: "July 21 – August 20" },
      payPeriodLabel: "July 21 – August 20",
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Board retreat travel.",
      additionalNotes: "Board retreat.",
      status: "approved",
      verificationStatus: "verified",
      payStatus: "paid",
      skipApproval: true,
      submittedAt: "2026-07-30T09:00:00.000Z",
      originalSubmittedAt: "7/30/2026 9:00",
      approvedByName: "Auto-approved (pending Admin verify)",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-07-30T11:00:00.000Z",
    },
    /* 13 — Admin (ADM002) submitted own leave → appears in MAN001's manager queue */
    {
      id: "MS-DEMO-013",
      source: "microsoft_forms",
      formResponseId: "DEMO-013",
      formType: "salaried",
      empId: "ADM002",
      empName: "Dana Okafor",
      initials: "DO",
      jobTitle: "Admin Coordinator",
      department: "Administration & Support",
      costCentre: "5000",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Personal Day",
      leaveDates: ["2026-05-29"],
      dayLabels: "2026-05-29",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Personal appointment.",
      additionalNotes: "Personal appointment.",
      status: "pending",
      verificationStatus: "needs_review",
      payStatus: "paid",
      submittedAt: "2026-05-23T08:30:00.000Z",
      originalSubmittedAt: "5/23/2026 8:30",
      approvedById: null,
      approvedByName: null,
    },
    /* 14 — Manager-approved, awaiting Admin verification */
    {
      id: "MS-DEMO-014",
      source: "microsoft_forms",
      formResponseId: "DEMO-014",
      formType: "hourly",
      empId: "HUG001",
      empName: "Marcus Hughes",
      initials: "MH",
      jobTitle: "Program Facilitator",
      department: "Programs & Outreach",
      costCentre: "6900",
      managerId: "MAN002",
      managerName: "Tessa Okonkwo",
      employmentType: "RFT Hourly",
      leaveType: "Paid Sick Leave",
      leaveDates: ["2026-05-26"],
      dayLabels: "2026-05-26",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Paid Sick Leave", hours: 10 }],
      totalHours: 10,
      shiftLength: "10 Hours",
      reason: "Migraine.",
      additionalNotes: "Migraine.",
      status: "approved",
      verificationStatus: "needs_review",
      payStatus: "paid",
      submittedAt: "2026-05-25T07:45:00.000Z",
      originalSubmittedAt: "5/25/2026 7:45",
      approvedById: "MAN002",
      approvedByName: "Tessa Okonkwo",
      approvedAt: "2026-05-25T13:00:00.000Z",
    },
    /* 15 — Posted to Manusonic by ADM002 (second posting admin, different postedBy) */
    {
      id: "MS-DEMO-015",
      source: "microsoft_forms",
      formResponseId: "DEMO-015",
      formType: "hourly",
      empId: "LIN002",
      empName: "Avery Lin",
      initials: "AL",
      jobTitle: "Intake Worker",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Hourly",
      leaveType: "Personal Day",
      leaveDates: ["2026-05-04"],
      dayLabels: "2026-05-04",
      days: 1,
      payPeriod: { start: "2026-04-21", end: "2026-05-20", label: PP_APR_MAY },
      payPeriodLabel: PP_APR_MAY,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Personal day.",
      additionalNotes: "Personal day.",
      status: "approved",
      verificationStatus: "posted",
      payStatus: "paid",
      submittedAt: "2026-05-01T09:00:00.000Z",
      originalSubmittedAt: "5/1/2026 9:00",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-05-01T15:00:00.000Z",
      verifiedBy: "ADM002",
      verifiedByName: "Dana Okafor",
      verifiedAt: "2026-05-02T10:00:00.000Z",
      postedToManusonic: true,
      postedAt: "2026-05-03T11:00:00.000Z",
      postedBy: "Dana Okafor",
      managerComment: "Approved.",
    },
    /* 16 — Rejected by manager with comment */
    {
      id: "MS-DEMO-016",
      source: "microsoft_forms",
      formResponseId: "DEMO-016",
      formType: "salaried",
      empId: "WEL003",
      empName: "Elena Wells",
      initials: "EW",
      jobTitle: "Overnight Shelter Worker",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Vacation",
      leaveDates: ["2026-06-05", "2026-06-06"],
      dayLabels: "2026-06-05, 2026-06-06",
      days: 2,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Vacation", hours: 16 }],
      totalHours: 16,
      shiftLength: "8 Hours",
      reason: "Long weekend away.",
      additionalNotes: "Long weekend away.",
      status: "rejected",
      verificationStatus: "rejected",
      payStatus: "paid",
      submittedAt: "2026-05-28T08:00:00.000Z",
      originalSubmittedAt: "5/28/2026 8:00",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-05-29T09:00:00.000Z",
      managerComment: "Two others already booked off those dates — please pick another week.",
    },
    /* 17 — Retroactive request logged in a past pay period */
    {
      id: "MS-DEMO-017",
      source: "microsoft_forms",
      formResponseId: "DEMO-017",
      formType: "salaried",
      empId: "NAK002",
      empName: "Priya Nakamura",
      initials: "PN",
      jobTitle: "Community Outreach Worker",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Paid Sick Leave",
      leaveDates: ["2026-03-04"],
      dayLabels: "2026-03-04",
      days: 1,
      payPeriod: { start: "2026-02-21", end: "2026-03-20", label: "February 21 – March 20" },
      payPeriodLabel: "February 21 – March 20",
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Paid Sick Leave", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Was out sick — logging retroactively.",
      additionalNotes: "Was out sick — logging retroactively.",
      retroactive: true,
      status: "approved",
      verificationStatus: "verified",
      payStatus: "paid",
      submittedAt: "2026-03-22T10:00:00.000Z",
      originalSubmittedAt: "3/22/2026 10:00",
      approvedById: "MAN001",
      approvedByName: "Jordan Mercer",
      approvedAt: "2026-03-22T14:00:00.000Z",
      verifiedBy: "ADM001",
      verifiedByName: "Morgan Price",
      verifiedAt: "2026-03-23T09:00:00.000Z",
    },
    /* 18 — Unmatched: misspelled name, no ID match */
    {
      id: "MS-DEMO-018",
      source: "microsoft_forms",
      formResponseId: "DEMO-018",
      formType: "salaried",
      empId: "",
      empName: "Elena Wellls",
      initials: "EW",
      jobTitle: "Overnight Shelter Worker",
      department: "Shelters & Housing",
      costCentre: "7800",
      managerId: "",
      managerName: "",
      employmentType: "RFT Salaried",
      leaveType: "Personal Day",
      leaveDates: ["2026-06-09"],
      dayLabels: "2026-06-09",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Personal day.",
      additionalNotes: "Name does not match the directory — possible spelling error.",
      status: "pending",
      verificationStatus: "needs_review",
      payStatus: "paid",
      unmatched: true,
      submittedAt: "2026-06-08T09:00:00.000Z",
      originalSubmittedAt: "6/8/2026 9:00",
      approvedById: null,
      approvedByName: null,
    },
    /* 19 — Unmatched: blank Employee ID */
    {
      id: "MS-DEMO-019",
      source: "microsoft_forms",
      formResponseId: "DEMO-019",
      formType: "hourly",
      empId: "",
      empName: "Taylor Brooks",
      initials: "TB",
      jobTitle: "Kitchen Assistant",
      department: "Food Services",
      costCentre: "7200",
      managerId: "",
      managerName: "",
      employmentType: "RFT Hourly",
      leaveType: "Paid Sick Leave",
      leaveDates: ["2026-06-10"],
      dayLabels: "2026-06-10",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Paid Sick Leave", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Sick.",
      additionalNotes: "No Employee ID was provided on the form.",
      status: "pending",
      verificationStatus: "needs_review",
      payStatus: "paid",
      unmatched: true,
      submittedAt: "2026-06-09T08:00:00.000Z",
      originalSubmittedAt: "6/9/2026 8:00",
      approvedById: null,
      approvedByName: null,
    },
    /* 20 — Admin override approval (manager had not yet acted) */
    {
      id: "MS-DEMO-020",
      source: "microsoft_forms",
      formResponseId: "DEMO-020",
      formType: "salaried",
      empId: "NAK002",
      empName: "Priya Nakamura",
      initials: "PN",
      jobTitle: "Community Outreach Worker",
      department: "Community Services",
      costCentre: "6100",
      managerId: "MAN001",
      managerName: "Jordan Mercer",
      employmentType: "RFT Salaried",
      leaveType: "Personal Day",
      leaveDates: ["2026-06-03"],
      dayLabels: "2026-06-03",
      days: 1,
      payPeriod: { start: "2026-05-21", end: "2026-06-20", label: PP_MAY_JUN },
      payPeriodLabel: PP_MAY_JUN,
      yearOfLeave: "2026",
      hourDistribution: [{ type: "Personal Day", hours: 8 }],
      totalHours: 8,
      shiftLength: "8 Hours",
      reason: "Family commitment.",
      additionalNotes: "Family commitment.",
      status: "approved",
      verificationStatus: "needs_review",
      payStatus: "paid",
      submittedAt: "2026-05-30T08:00:00.000Z",
      originalSubmittedAt: "5/30/2026 8:00",
      approvedById: "ADM001",
      approvedByName: "Morgan Price",
      approvedAt: "2026-06-04T09:30:00.000Z",
      overrideApproval: {
        reason: "Manager away on leave and payroll cutoff approaching — approved on their behalf.",
        adminName: "Morgan Price",
        adminId: "ADM001",
        timestamp: "2026-06-04T09:30:00.000Z",
      },
      auditTrail: [
        {
          type: "override_approval",
          overrideReason: "Manager away on leave and payroll cutoff approaching — approved on their behalf.",
          adminName: "Morgan Price",
          adminId: "ADM001",
          timestamp: "2026-06-04T09:30:00.000Z",
        },
      ],
    },
  ];

  const finalRequests = requests.map((r) => {
    if (!r.leaveType || r.leaveType === "—") {
      r.leaveType = r.hourDistribution?.length ? summarizeLeaveTypes(r.hourDistribution) : "—";
    }
    return enrichRequest(r, employees);
  });

  return {
    version: 6,
    seeded: true,
    demoData: true,
    appName: "Hope Mission LRF",
    session: { empId: "ADM001", interface: "manusonic" },
    employees,
    requests: finalRequests,
    nextRequestNum: 20,
    staffImports: [],
  };
}

module.exports = { getSeedStore, lastNamePrefix, assignEmployeeIds };
